language: csharp
dist: xenial
os:
  - linux
  - osx
mono: latest
dotnet: 2.1.603

cache:
  directories:
    - tools

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

git:
  depth: false

branches:
  only:
    - master
    - develop
    - /release\/.*/
    - /hotfix\/.*/
    - /feature\/.*/

script:
  - ./build.sh --verbosity=Verbose
