name: Close Milestones

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1.6.0
        with:
          dotnet-version: 3.1.x
      - name: Build with cake
        uses: cake-build/cake-action@v1.1.1
        with:
          script-path: setup.cake
          target: Close-Milestones
          verbosity: Diagnostic
          cake-version: 0.38.1
          cake-bootstrap: true
